### ISSUE TITLE
Jobs are not being queued

### ISSUE THREAD

**Issue by agustin** [anjlab/sunspot_offline#1]
Hi there! hope you're having a great day! just wondering if there is some other config that should be set in order for the jobs to be queued.

I'm correctly not having any errors, but neither jobs in the corresponding queue.

I'm testing it with Rails 6 and Sidekiq 6, and doing a `.reindex` on the class, maybe it's because of something I'm missing! 
Thanks for the work on this gem an on sunspot as well! 
Cheers

**Comment by serggl** [comment]
this gem starts to work when you have Solr down. Otherwise all your `.reindex` calls will work in a normal way (synchronous)

**Comment by agustin** [comment]
Hi @serggl thanks for the followup! I'm sure I tested locally with the Solr server down, but must not be the case because I just ensure that the conditions are met and everything work as expected 🤦 ! sorry for this!

Also notice that, at least with the `.reindex` call 2 jobs are queue, despite the fact that the `RemovalWorker` has `nil` as the argument, not sure if this is the expected behaviour or if there is nothing to do then maybe the job should not be queued, is that right? If this makes no sense, no worries!

Thanks again! and have a great day! Feel free to close this issue!
